config/routes.rb
Rails.application.routes.draw do
  get 'homes/about'
  devise_for :users, controllers: {
   omniauth_callbacks: 'users/omniauth_callbacks',
   registrations: 'users/registrations'
 }

  root 'homes#top'
  get '/search' => 'searchs#search'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :posts do
    resource :favorites, only: [:create, :destroy, :index]
    resources :post_comments, only: [:create, :destroy, :show]
  end

  get 'post/ranking' => 'posts#rank'
  get 'post/random' => 'posts#random'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:twitter]

  attachment :profile_image

  attr_accessor :twitter_image_url

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :sns_credentials, dependent: :destroy
  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.from_omniauth(auth)
   sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
   user = User.where(email: auth.info.email).first_or_initialize(
    name: auth.info.name,
    email: auth.info.email
    )
    user.twitter_image_url = auth.info.image
   if user.persisted?
     sns.user = user
     sns.save
   end
   { user: user, sns: sns }
  end

  validates :name, presence: true
  validates :name, length: { minimum: 1, maximum: 20 }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
   def twitter
    authorization
   end

   private

   def authorization
     sns_info = User.from_omniauth(request.env["omniauth.auth"])
     @user = sns_info[:user]
      if @user.persisted? #ユーザー情報が登録済みなので、新規登録ではなくログイン処理を行う
        sign_in_and_redirect @user, event: :authentication
      else #ユーザー情報が未登録なので、新規登録画面へ遷移する
        @sns_id = sns_info[:sns].id
        render template: 'devise/registrations/new'
      end
   end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true
require 'open-uri'

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  #POST /resource
  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    # user.profile_image = open(auth.info.image)
    super
    # resource = User.new(use_params)
    # resource.save
    if params[:user][:twitter_image_url].present?
      resource.profile_image = open(params[:user][:twitter_image_url])
      resource.save
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order("created_at DESC").page(params[:page]).per(15)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order("created_at DESC").page(params[:page]).per(5)
    #ユーザーに紐ずくいいね数
    @user_posts = @user.posts
    # 変数を定義し、0を代入。
    @favorites_count = 0
    # countメソッドを使い、１つの投稿に結びつくイイねを予め定義しておいた@favorites_countに足していく。
    @user_posts.each do |post|
      @favorites_count += post.favorites.count
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
        redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :introduction, :profile_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_errors.html.erb
<% if user.errors.any? %>
  <div class="alert alert-danger alert-dismissible text-center" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-lebel="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <div class="fas fa-exclamation-triangle mb-2 ml-2">
      <span class="font-weight-normal">&thinsp;以下の内容をご確認ください</span>
    </div>
    <div>
      <% user.errors.full_messages.each do |message| %>
        <strong class="ml-3"><%= message %></strong><br />
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/_index.html.erb
<% if users.blank? %>
  <h4 class="mt-3">ユーザーはいません。<h4>
<% else %>
  <table class="table table-striped mt-4 table-sm">
    <thread>
      <tr>
        <th class="text-left"></th>
        <th>Name</th>
        <th></th>
      </tr>
    </thread>
    <tbody>
      <% users.each do |user| %>
        <tr id="user_<%= user.id %>">
          <td class="text-left align-bottom">
             <%= link_to user_path(user.id) do %>
               <%= attachment_image_tag user, :profile_image, :fill, 35, 35, format: 'jpeg', fallback: "no-image.jpg", size: "35x35", class:"rounded-circle shadow-sm"; %>
             <% end %>
          </td>
          <td class="align-bottom">
            <%= link_to user_path(user.id) do %>
              <%= user.name %>
            <% end %>
          </td>
          <td class="align-bottom">
            <span class="follow-btn">
              <%= render '/relationships/follow_btn', user: user %>
            </span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<div class="row">
  <div class="mx-auto mt-2 h2">
    <%= paginate users %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="topic">
  <div class="container">
    <h1 class="mt-4 topic-font">編集ページ</h1>
  </div>
</div>

<div class="container">
  <% if @user.errors.any? %>
    <div class="notification is-danger">
      <h2><%= pluralize(@user.errors.count, "つのエラーにより") %>保存に失敗しました。</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="main">
    <div class="form-wrap">
    <%= render "users/errors", user: @user %>
　　<%= form_with model: @user, url: user_path(@user), method: :patch, local:true do |f| %>
      <div class="form-group mb-4">
        <%= f.label "お名前", class: "font-weight-bold mb-2" %>（1文字以上20文字以内）<br />
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group mb-4">
        <%= f.label "メールアドレス", class: "font-weight-bold" %>（半角英数字）<br />
        <%= f.email_field :email, class: "form-control" %>
      </div>

      <div class="form-group mb-4">
        <%= f.label :profile_image, "プロフィール画像", class: "font-weight-bold" %>
        <%= f.attachment_field :profile_image, class: "input" %>
      </div>

      <div class="form-group">
        <%= f.label "自己紹介", class: "font-weight-bold" %><br />
        <%= f.text_area :introduction, class: "form-control js-text", rows: 6 %>
        <p class="js-text-count text-right mt-1"></p>
      </div>

      <div class="actions">
        <%= f.submit "編集を完了する", class: "btn btn-primary btn-shadow w-100" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7 col-xs-12 mx-auto">
      <h4 class="border-bottom border-gray mt-4 text-center">
        <i class="fas fa-users"></i> ユーザー一覧
      </h4>
      <%= render '/users/index', users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7 col-xs-12 mx-auto">
      <h5 class="mt-4 font-weight-bold">
        <%= @user.name %>
      </h5>
      <div class="row pb-3 border-bottom border-gray">
        <div class="col-4 ml-1 text-center">
          <%= attachment_image_tag @user, :profile_image, :fill, 110, 110, format: 'jpeg', fallback: "no-image.jpg", size: "110x110", class:"rounded-circle shadow-sm mt-2"; %>
          <% if user_signed_in? %>
            <span class="show-follow-btn">
              <%= render '/relationships/follow_btn', user: @user %>
            </span>
            <% if @user == current_user %>
              <%= link_to "会員情報の編集",edit_user_path(@user), data: {"turbolinks" => false}, class:"btn-secondary btn mt-4 btn-sm btn-block"; %>
            <% end %>
          <% end %>
        </div>
        <div class="col-7 ml-1">
          <table class="table-sm font-weight-bold">
            <tbody>
              <tr>
                <th>
                  <i class="fas fa-thumbs-up text-danger"></i> 総数
                </th>
                <td>
                <span class="favorites-count">
                  <%= @favorites_count %>
                </span>
                </td>
              </tr>
              <tr>
                <th>
                  <i class="fas fa-camera"></i> 投稿
                </th>
                <td>
                  <%= @user.posts.count %>
                </td>
              </tr>
              <tr>
                <th>
                  フォロー
                </th>
                <td>
                  <%= link_to user_followings_path(@user) do %>
                    <%= @user.followings.count %>
                  <% end %>
                </td>
              </tr>
              <tr>
                <th>
                  フォロワー
                </th>
                <td>
                  <%= link_to user_followers_path(@user) do %>
                   <%= @user.followers.count %>
                  <% end %>
                </td>
              </tr>
            </tbody>
          </table>
          <%= @user.introduction %>
        </div>
      </div>
      <h5 class="border-bottom border-gray mt-5 font-weight-bold">
        <i class="fas fa-camera"></i> このユーザーの投稿
      </h5>
      <%= render '/posts/index', posts: @posts %>
    </div>
  </div>
</div>