config/routes.rb
Rails.application.routes.draw do
  get 'homes/about'
  devise_for :users, controllers: {
   omniauth_callbacks: 'users/omniauth_callbacks',
   registrations: 'users/registrations'
 }

  root 'homes#top'
  get '/search' => 'searchs#search'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :posts do
    resource :favorites, only: [:create, :destroy, :index]
    resources :post_comments, only: [:create, :destroy, :show]
  end

  get 'post/ranking' => 'posts#rank'
  get 'post/random' => 'posts#random'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  attachment :post_image
  
  validates :title, :post_content, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.page(params[:page]).page(params[:page]).per(5).order(created_at: :desc)
  end

  def rank
    @posts = Post.find(Favorite.group(:post_id).pluck(:post_id))
    @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(5)
  end

  def random
    if ActiveRecord::Base.connection_config[:adapter] == 'sqlite3'  #ローカル。DBで判断
    @posts = Post.order("RANDOM()").limit(5)
    else
    @posts = Post.order("RAND()").limit(5)
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.score = Language.get_data(post_params[:post_content])
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end

  def edit
    @post = Post.find(params[:id])
    if @post.user != current_user
      redirect_to post_path(@post.id)
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    if post.user == current_user
      post.destroy
      flash[:notice] = "投稿が削除されました。"
    else
      flash[:alert] = "投稿の削除に失敗しました。"
    end
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :post_content, :post_image)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_errors.html.erb
<% if post.errors.any? %>
  <div class="alert alert-danger alert-dismissible text-center" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-lebel="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <div class="fas fa-exclamation-triangle mb-2 ml-2">
      <span class="font-weight-normal">&thinsp;以下の内容をご確認ください</span>
    </div>
    <div>
      <% post.errors.full_messages.each do |message| %>
        <strong class="ml-3"><%= message %></strong><br />
      <% end %>
    </div>
  </div>
<% end %>

app/views/posts/_index.html.erb
<% posts.each do |post| %>
  <article class="mt-5 shadow-lg mx-auto pb-1">
    <%= link_to attachment_image_tag(post, :post_image, fallback: "no-image.jpg", class: "card-img-top card-img-lg"),  post_path(post)%>

    <h2 class="font-weight-bold m-3 text-center">
      <%= link_to truncate(post.title, length: 15), post_path(post.id) %>
    </h2>

    <nav class="navbar-expand border-bottom border-gray m-3">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item ml-4 h5">
          <%= link_to post.user.name, user_path(post.user.id), class: "fas fa-user" %>
        </li>

        <li class="nav-item ml-4 h5">
          <%= link_to post.post_comments.count, post_path(post.id), class: "fas fa-comment" %>
        </li>

        <li class="nav-item ml-4 h5 favorite-btn_<%= post.id %>">
          <%= render "favorites/favorite-btn", post: post %>
        </li>
      </ul>
    </nav>
  </article>
<% end %>

<div class="row">
  <div class="pagination mx-auto">
    <%= paginate posts %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="topic">
  <div class="container">
    <h1 class="mt-4 topic-font">編集</h1>
  </div>
</div>

<div class="container">
  <div class="main">
    <div class="form-wrap">
    <%= render "posts/errors", post: @post %>
　　<%= form_with model: @post, url: post_path, local:true do |f| %>
　　  <div class="form-group mb-4">
        <%= f.label :post_image, "画像", class: "font-weight-bold" %>
        <%= f.attachment_field :post_image, class: "input" %>
      </div>

      <div class="form-group mb-4">
        <%= f.label "タイトル", class: "font-weight-bold mb-2" %><br />
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group mb-4">
        <%= f.label "本文", class: "font-weight-bold" %><br />
        <%= f.text_field :post_content, class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit "投稿する", class: "btn btn-primary btn-shadow w-100" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7 col-xs-12 mx-auto">
      <h5 class="border-bottom border-gray mt-4 font-weight-bold text-center">
        みんなの投稿
      </h5>
      <nav class="navbar-expand mt-2">
        <ul class="navbar-nav ml-auto nav-tabs">
          <li class="nav-item ml-4 nav-link active">
            <%= link_to "新着", posts_path %>
          </li>
          <li class="nav-item ml-4 nav-link">
            <%= link_to "人気", post_ranking_path %>
          </li>
          <li class="nav-item ml-4 nav-link">
            <%= link_to "ランダム5", post_random_path %>
          </li>
        </ul>
      </nav>
      <%= render '/posts/index', posts: @posts %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="topic">
  <div class="container">
    <h1 class="mt-4 topic-font">新規投稿</h1>
  </div>
</div>

<div class="container">
  <div class="main">
    <div class="form-wrap">
    <%= render "posts/errors", post: @post %>
　　<%= form_with model: @post, url: posts_path, local:true do |f| %>
　　  <div class="form-group mb-4">
        <%= f.label :post_image, "画像", class: "font-weight-bold" %>
        <%= f.attachment_field :post_image, class: "input" %>
      </div>

      <div class="form-group mb-4">
        <%= f.label "タイトル", class: "font-weight-bold mb-2" %><br />
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group mb-4">
        <%= f.label "本文", class: "font-weight-bold" %><br />
        <%= f.text_field :post_content, class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit "投稿する", class: "btn btn-primary btn-shadow w-100" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/posts/random.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7 col-xs-12 mx-auto">
      <h5 class="border-bottom border-gray mt-4 font-weight-bold text-center">
        みんなの投稿
      </h5>
      <nav class="navbar-expand mt-2">
        <ul class="navbar-nav ml-auto nav-tabs">
          <li class="nav-item ml-4 nav-link">
            <%= link_to "新着", posts_path %>
          </li>
          <li class="nav-item ml-4 nav-link">
            <%= link_to "人気", post_ranking_path %>
          </li>
          <li class="nav-item ml-4 nav-link active">
            <%= link_to "ランダム5", post_random_path %>
          </li>
        </ul>
      </nav>
      <% @posts.each do |post| %>
        <article class="mt-5 shadow-lg mx-auto pb-1">
          <%= link_to attachment_image_tag(post, :post_image, fallback: "no-image.jpg", class: "card-img-top card-img-lg"),  post_path(post)%>
      
          <h2 class="font-weight-bold m-3 text-center">
            <%= link_to truncate(post.title, length: 8), post_path(post.id) %>
          </h2>
      
          <nav class="navbar-expand border-bottom border-gray m-3">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item ml-4 h5">
                <%= link_to post.user.name, user_path(post.user.id), class: "fas fa-user" %>
              </li>
      
              <li class="nav-item ml-4 h5">
                <%= link_to post.post_comments.count, post_path(post.id), class: "fas fa-comment" %>
              </li>
      
              <li class="nav-item ml-4 h5 favorite-btn_<%= post.id %>">
                <%= render "favorites/favorite-btn", post: post %>
              </li>
            </ul>
          </nav>
        </article>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/rank.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7 col-xs-12 mx-auto">
      <h5 class="border-bottom border-gray mt-4 font-weight-bold text-center">
        みんなの投稿
      </h5>
      <nav class="navbar-expand mt-2">
        <ul class="navbar-nav ml-auto nav-tabs">
          <li class="nav-item ml-4 nav-link">
            <%= link_to "新着", posts_path %>
          </li>
          <li class="nav-item ml-4 nav-link active">
            <%= link_to "人気", post_ranking_path %>
          </li>
          <li class="nav-item ml-4 nav-link">
            <%= link_to "ランダム5", post_random_path %>
          </li>
        </ul>
      </nav>
      <%= render '/posts/index', posts: @posts %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7 col-xs-12 mx-auto">
      <article class="mt-4 shadow-lg">
        <%= attachment_image_tag @post, :post_image, fallback: "no-image.jpg", class: "card-img-top card-img-lg" %>
        <h2 class="border-bottom border-gray font-weight-bold m-3 text-center">
          <%= @post.title %>
        </h2>

        <h5 class="border-bottom border-gray font-weight-bold m-3 text-center">
          <%= @post.post_content %>
          <!--↓↓自然言語処理-->
          <!--<p class="sentiment-score">[<%#= @post.score %>]</p>-->
        </h5>

        <nav class="navbar-expand border-bottom border-gray m-3">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item ml-4 h5">
              <%= link_to @post.user.name, user_path(@post.user.id), class: "fas fa-user" %>
            </li>

            <li class="nav-item ml-4 h5">
              <%= link_to @post.post_comments.count, post_path(@post), class: "fas fa-comment" %>
            </li>

            <li class="nav-item ml-4 h5 favorite-btn_<%= @post.id %>">
              <%= render "favorites/favorite-btn", post: @post %>
            </li>

            <% if @post.user_id == current_user.id %>
            <li class="nav-item ml-4 h5">
              <%= link_to edit_post_path(@post) do %>
                <i class="fas fa-edit"></i>
              <% end %>
            </li>

            <li class="nav-item ml-4 h5">
              <%= link_to  post_path(@post), method: :delete, data: {confirm: "削除しますか？"} do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            </li>
            <% end %>

          </ul>
        </nav>

        <div class="m-3 comments">
          <%= render "post_comments/comments", post: @post %>
        </div>

        <div class="new-comment">
          <div class="comments-error">
            <%= render "post_comments/errors", post_comment: @post_comment %>
          </div>
          <%= form_with(model:[@post, @post_comment], remote: true) do |f| %>
            <%= f.text_field :comment, rows:'4', class: "mt-2 w-100", placeholder: "コメントを入力" %>
            <%= f.submit "送信する", class: "mt-2 btn btn-info btn-block w-100" %>
          <% end %>
        </div>
      </article>
    </div>
  </div>
</div>