config/routes.rb
Rails.application.routes.draw do
  get 'homes/about'
  devise_for :users, controllers: {
   omniauth_callbacks: 'users/omniauth_callbacks',
   registrations: 'users/registrations'
 }

  root 'homes#top'
  get '/search' => 'searchs#search'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :posts do
    resource :favorites, only: [:create, :destroy, :index]
    resources :post_comments, only: [:create, :destroy, :show]
  end

  get 'post/ranking' => 'posts#rank'
  get 'post/random' => 'posts#random'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  attachment :post_image
  
  validates :title, :post_content, presence: true
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:twitter]

  attachment :profile_image

  attr_accessor :twitter_image_url

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :sns_credentials, dependent: :destroy
  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.from_omniauth(auth)
   sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
   user = User.where(email: auth.info.email).first_or_initialize(
    name: auth.info.name,
    email: auth.info.email
    )
    user.twitter_image_url = auth.info.image
   if user.persisted?
     sns.user = user
     sns.save
   end
   { user: user, sns: sns }
  end

  validates :name, presence: true
  validates :name, length: { minimum: 1, maximum: 20 }
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = Favorite.all
  end
  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: @post.id)
    favorite.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    if ActiveRecord::Base.connection_config[:adapter] == 'sqlite3'  #ローカル。DBで判断
    @posts = Post.order("RANDOM()").limit(3)
    else
    @posts = Post.order("RAND()").limit(3)
    end
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.page(params[:page]).page(params[:page]).per(5).order(created_at: :desc)
  end

  def rank
    @posts = Post.find(Favorite.group(:post_id).pluck(:post_id))
    @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(5)
  end

  def random
    if ActiveRecord::Base.connection_config[:adapter] == 'sqlite3'  #ローカル。DBで判断
    @posts = Post.order("RANDOM()").limit(5)
    else
    @posts = Post.order("RAND()").limit(5)
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.score = Language.get_data(post_params[:post_content])
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end

  def edit
    @post = Post.find(params[:id])
    if @post.user != current_user
      redirect_to post_path(@post.id)
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    if post.user == current_user
      post.destroy
      flash[:notice] = "投稿が削除されました。"
    else
      flash[:alert] = "投稿の削除に失敗しました。"
    end
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :post_content, :post_image)
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def search
    @posts = Post.joins(:user).where('title LIKE ? OR post_content LIKE ? OR name LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%") if params[:search].present?
    @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(5)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order("created_at DESC").page(params[:page]).per(15)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order("created_at DESC").page(params[:page]).per(5)
    #ユーザーに紐ずくいいね数
    @user_posts = @user.posts
    # 変数を定義し、0を代入。
    @favorites_count = 0
    # countメソッドを使い、１つの投稿に結びつくイイねを予め定義しておいた@favorites_countに足していく。
    @user_posts.each do |post|
      @favorites_count += post.favorites.count
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
        redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="text-center">
      <p class="mt-3">
        Copyright © OwaraiBiyori
      </p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/"><%= image_tag('logo.png') %></a>
  <% if user_signed_in? %>
    <div class="navbar-nav">
      <%= form_with url: search_path, method: :get, local: true do |f| %>
      <%= f.text_field :search , placeholder: 'キーワードを入力'%>
      <%= f.submit '検索', name: nil %>
      <% end %>
    </div>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-md-auto align-items-center">
      <% if user_signed_in? %>
        <li><%= link_to " 投稿する", new_post_path, class: "fas fa-plus-circle nav-link text-light" %></li>
        <li>
          <%= link_to user_path(current_user), {class:"nav-link text-light"} do %>
            <%= attachment_image_tag(current_user, :profile_image, fallback: "no-image.jpg", size:"25x25", class: "rounded-circle shadow-sm") %>
          <% end %>
        </li>
        <li style="margin-left:-10px">
          <%= link_to "マイページ", user_path(current_user), class:"nav-link text-light" %>
        </li>
        <li><%= link_to " ユーザー一覧", users_path, class: "fas fa-users nav-link text-light" %></li>
        <li><%= link_to " 投稿一覧", posts_path,class: "fas fa-camera nav-link text-light" %></li>
        <li><%= link_to " ログアウト", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %></li>
      <% else %>
        <li><%= link_to " トップページ", root_path, class: "fas fa-home nav-link text-light" %></li>
        <li><%= link_to " 会員登録", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %></li>
        <li><%= link_to " 会員様はこちら", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!--<meta name="viewport" content="width=device-width,initial-scale=1.0">-->
    <title>OwaraiBiyori</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/cec8123f02.js" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>